### ISSUE TITLE
AttributeError: module 'custom_components.sensor.krisinformation' has no attribute 'setup_platform'

### ISSUE THREAD

**Issue by rasssta** [isabellaalstrom/sensor.krisinformation#3]
Tried to install this component but got the following error:

2019-02-23 13:07:41 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform krisinformation
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'custom_components.sensor.krisinformation' has no attribute 'setup_platform'

**Comment by isabellaalstrom** [comment]
Are you on home assistant v.0.88 or above and have you updated or manually changed to the latest version of how components are supposed to be in the folder structure?

**Comment by rasssta** [comment]
I am on 0.87.0. What changes do I need to perform when upgrading to =>0.88?

**Comment by isabellaalstrom** [comment]
That's weird, you shouldn't get that issue then. Follow the new folder structure that is in this repo, and add empty __init__.py file.

**Comment by rasssta** [comment]
Works fine on 0.88.1! :)
